services:
  swan:
    build: 
      context: .
    ports:
      - "8888:8888"
    volumes:
    - .:/app 
    - ./weights:/weights
    - ./comfyui_models:/comfyui_models
    environment:
      - PYTHONPATH=/app/swan
    deploy:
      resources:
          reservations:
              devices:
                  - driver: nvidia
                    count: all
                    capabilities: [all]